FROM renegademaster/zomboid-dedicated-server:latest

COPY amd64-entrypoint.sh /home/steam/amd64-entrypoint.sh
COPY configure-server.sh /home/steam/configure-server.sh
COPY mods/ZomboidManager /opt/zomboid-manager

RUN apt-get update \
    && apt-get install -y --no-install-recommends jq \
    && rm -rf /var/lib/apt/lists/*

RUN chmod +x /home/steam/amd64-entrypoint.sh /home/steam/configure-server.sh
